# Generated by Django 5.0.6 on 2024-06-14 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("duracion", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("dni", models.IntegerField(unique=True)),
                ("correo", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("dni", models.IntegerField(unique=True)),
                ("correo", models.EmailField(max_length=50)),
                (
                    "ciclo_culmidado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Primer Ciclo"),
                            ("2", "Segundo Ciclo"),
                            ("3", "Tercer Ciclo"),
                            ("4", "Cuarto Ciclo"),
                            ("5", "Quinto Ciclo"),
                            ("6", "Sexto Ciclo"),
                            ("7", "Septimo Ciclo"),
                            ("8", "Octavo Ciclo"),
                            ("9", "Noveno Ciclo"),
                            ("10", "Decimo Ciclo"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "ciclo",
                    models.CharField(
                        choices=[
                            ("1", "Primer Ciclo"),
                            ("2", "Segundo Ciclo"),
                            ("3", "Tercer Ciclo"),
                            ("4", "Cuarto Ciclo"),
                            ("5", "Quinto Ciclo"),
                            ("6", "Sexto Ciclo"),
                            ("7", "Septimo Ciclo"),
                            ("8", "Octavo Ciclo"),
                            ("9", "Noveno Ciclo"),
                            ("10", "Decimo Ciclo"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uni.carrera",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=5, unique=True)),
                (
                    "carrera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uni.carrera",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("creditos", models.IntegerField()),
                ("horas", models.IntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uni.carrera",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uni.ciclo",
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uni.profesor",
                    ),
                ),
            ],
        ),
    ]
