# Generated by Django 5.0.6 on 2024-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni", "0002_alter_carrera_nombre_alter_ciclo_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciclo",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
    ]
