# Generated by Django 5.0.6 on 2024-06-15 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uni", "0005_alter_alumno_ciclo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrera",
            old_name="duracion",
            new_name="duracion_ciclos",
        ),
    ]
