# Generated by Django 5.0.6 on 2024-06-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uni", "0006_rename_duracion_carrera_duracion_ciclos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="ciclo",
            field=models.IntegerField(null=True),
        ),
    ]
